export { default as Home } from './Home'
export { default as Work } from './Work'
export { default as Contact } from './Contact'
export { default as Development } from './services/Development'
export { default as Design } from './services/Design'
export { default as Consulting } from './services/Consulting'
export { default as Education } from './services/Education'